##Define two identical production environments (Blue and Green).
Deploy new versions to the inactive environment and switch traffic when ready.##

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      color: blue
  template:
    metadata:
      labels:
        app: nodejs-app
        color: blue
    spec:
      containers:
      - name: nodejs-app
        image: your-registry-url/nodejs-app:latest
        ports:
        - containerPort: 8080
