apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      color: green
  template:
    metadata:
      labels:
        app: nodejs-app
        color: green
    spec:
      containers:
      - name: nodejs-app
        image: your-registry-url/nodejs-app:latest
        ports:
        - containerPort: 8080
